package com.internship.cristi.internshipapp.utils;

import android.content.Context;
import android.content.Intent;
import android.util.Log;

/**
 * Created by cristi on 1/13/18.
 */

public class SendEmail {

    String email;
    String EMAIL_TEXT = "Welcome to our new internship app! This is an autogenerated Email";
    String EMAIL_SUBJECT = "Welcome to our internship app";
    String EMAIL_SENDER = "cristiantamas05@gmail.com";
    String PASSWORD = "cristysk8";


    public SendEmail(String email) {
        this.email = email;;
    }

    public int sendEmail(){
        final int status = 0;
        /*BackgroundMail.newBuilder(this)
                .withUsername(EMAIL_SENDER)
                .withPassword(PASSWORD)
                .withMailto(email)
                .withType(BackgroundMail.TYPE_PLAIN)
                .withSubject(EMAIL_SUBJECT)
                .withBody(EMAIL_TEXT)
                .withOnSuccessCallback(new BackgroundMail.OnSuccessCallback() {
                    @Override
                    public void onSuccess() {
                        status = 1;
                    }
                })
                .withOnFailCallback(new BackgroundMail.OnFailCallback() {
                    @Override
                    public void onFail() {
                        Log.d("Mail sender:", "something went wrong");
                    }
                })
                .send();*/

        return status;
    }
}
